services:
  postgres-db:
    image: postgres:15
    container_name: risencore-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  risencore-backend:
    build:
      context: ./backend
    container_name: risencore-backend-app
    restart: on-failure
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${DB_NAME}
      - SPRING_PROFILES_ACTIVE=dev

  risencore-frontend:
    build:
      context: ./frontend
    container_name: risencore-frontend-app
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src

volumes:
  postgres-data: