version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: risencore-postgres
    restart: always
    environment:
      POSTGRES_DB: risencore_db
      POSTGRES_USER: risencore_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  risencore-backend:
    build:
      context: ./backend
    container_name: risencore-backend-app
    restart: on-failure
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/risencore_db
      SPRING_DATASOURCE_USERNAME: risencore_user
      SPRING_DATASOURCE_PASSWORD: password123
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate

  risencore-frontend:
    build:
      context: ./frontend
    container_name: risencore-frontend-app
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src

volumes:
  postgres-data: