-- Create the transactions table to store financial records
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    amount NUMERIC(19, 4) NOT NULL, -- NUMERIC is the standard SQL type for BigDecimal
    type VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    transaction_date DATE NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_transactions_on_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE
);

-- Optional: Create an index on the user_id and transaction_date for faster queries
CREATE INDEX idx_transactions_user_id ON transactions(user_id);
CREATE INDEX idx_transactions_transaction_date ON transactions(transaction_date);