-- Create the habits table to store user-defined habits
CREATE TABLE habits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    frequency VARCHAR(255) NOT NULL, -- Will store 'DAILY' or 'WEEKLY'
    target_count INT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_habits_on_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE
);

-- Create the habit_completions table to track when a habit is completed
CREATE TABLE habit_completions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    completion_date DATE NOT NULL,
    habit_id BIGINT NOT NULL,
    CONSTRAINT fk_completions_on_habit FOREIGN KEY (habit_id) REFERENCES habits(id) ON DELETE CASCADE,
    -- A user should only be able to mark a habit as complete once per day
    CONSTRAINT uq_habit_completion_date UNIQUE (habit_id, completion_date)
);

-- Create indexes for performance
CREATE INDEX idx_habits_user_id ON habits(user_id);
CREATE INDEX idx_completions_habit_id ON habit_completions(habit_id);